CREATE TABLE "GAB_5326_APRVL"(
 "PURCHASE_ORDER" VARCHAR(7) NOT NULL ,
 "DATE_ORDER" DATE NOT NULL,
 "VENDOR" VARCHAR(6) NOT NULL ,
 "AMOUNT" NUMERIC(15,2),
 "DATE_DUE" DATE NOT NULL ,
 "ORIGINATOR" VARCHAR(8) NOT NULL ,
 "APPROVER" VARCHAR(8),
 "APPROVED_DATE" DATETIME,
 PRIMARY KEY(PURCHASE_ORDER,DATE_ORDER));

CREATE TABLE "GAB_5326_APRVRS"(
 "GS_USER" VARCHAR(8) NOT NULL ,
 "APPROVER" VARCHAR(8) NOT NULL);

CREATE TABLE "GAB_5326_DOL_LMT"(
 "GS_USER" VARCHAR(8) NOT NULL ,
 "AMOUNT_LIMIT" NUMERIC(15,2),
 PRIMARY KEY(GS_USER));